# Stage 03 - Python Fundamentals Summary

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from datetime import datetime

In [2]:
# Create an array and perform element-wise operations

lst_1 = np.arange(1,11)
print(lst_1)
print(lst_1 + 2)
print(lst_1 * 2)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  4  5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12 14 16 18 20]


In [3]:
# Vectorization v.s. Loops

big_array = np.arange(10000)
%timeit [x * 2 for x in big_array]
%timeit big_array * 2

501 µs ± 3.68 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
3.65 µs ± 31.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [4]:
# Load the starter data file and inspect

df = pd.read_csv('/Users/willwu/Desktop/NYU Tandon/FRE-GY/5040 Foundations of Applied Financial Engineering/bootcamp_will_wu/homework/stage03/data/starter_data.csv')
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   category  10 non-null     object
 1   value     10 non-null     int64 
 2   date      10 non-null     object
dtypes: int64(1), object(2)
memory usage: 368.0+ bytes


category  value        date
0        A     10  2025-08-01
1        B     15  2025-08-02
2        A     12  2025-08-03
3        B     18  2025-08-04
4        C     25  2025-08-05

In [6]:
# Describe

df.describe()

value
count  10.000000
mean   17.600000
std     7.381659
min    10.000000
25%    12.250000
50%    14.500000
75%    23.250000
max    30.000000

In [8]:
# Summary Statistics from utility functions

import sys
import os
sys.path.append(os.path.abspath('..'))

from src.utils import get_summary_stats
get_summary_stats(df)

column  count  mean       std   min    25%   50%    75%   max  missing
0  value   10.0  17.6  7.381659  10.0  12.25  14.5  23.25  30.0        0

In [10]:
# Groupby aggregation

from src.utils import pick_category_column

cat_col = pick_category_column(df)
if cat_col:
    num_cols = df.select_dtypes(include = 'number').columns
    group_summary = (df.groupby(cat_col)[num_cols]
                       .agg(['count','mean','median','sum']))
    group_summary.columns = ['_'.join(c).strip() for c in group_summary.columns]
    group_summary = group_summary.reset_index()
    display(group_summary)

category  value_count  value_mean  value_median  value_sum
0        A            4   11.500000          11.5         46
1        B            3   15.666667          15.0         47
2        C            3   27.666667          28.0         83

The two utility functions created  (`get_summary_stats` and `pick_category_column`) are documented in `src/utils.py` and explained in `src/utils.md`. 